#!/usr/bin/env bash

# Shared configuration for the dual RNA-seq alignment pipeline.
# Source this file from workflow scripts, then override values with environment
# variables when needed, for example: THREADS=32 bash dual_rnaseq_workflow.sh.

WORKDIR="${WORKDIR:-/home/lshpk18/OzanGundogdu_SOUK011275}"
ANALYSIS_DIR="${ANALYSIS_DIR:-$WORKDIR/Analysis}"
ALIGNMENT_DIR="${ALIGNMENT_DIR:-$ANALYSIS_DIR/Alignment}"

TRIM_DIR="${TRIM_DIR:-$ANALYSIS_DIR/trim_results}"
REF_DIR="${REF_DIR:-$ALIGNMENT_DIR/references}"
STAR_INDEX_DIR="${STAR_INDEX_DIR:-$ALIGNMENT_DIR/star_index}"
HOST_STAR_INDEX_DIR="${HOST_STAR_INDEX_DIR:-$STAR_INDEX_DIR/host}"
BACTERIA_STAR_INDEX_DIR="${BACTERIA_STAR_INDEX_DIR:-$STAR_INDEX_DIR/bacteria}"

ALIGN_DIR="${ALIGN_DIR:-$ALIGNMENT_DIR/alignments}"
HOST_ALIGN_DIR="${HOST_ALIGN_DIR:-$ALIGN_DIR/host}"
BACTERIA_ALIGN_DIR="${BACTERIA_ALIGN_DIR:-$ALIGN_DIR/bacteria}"

BAM_DIR="${BAM_DIR:-$ALIGNMENT_DIR/bam}"
HOST_BAM_DIR="${HOST_BAM_DIR:-$BAM_DIR/host}"
BACTERIA_BAM_DIR="${BACTERIA_BAM_DIR:-$BAM_DIR/bacteria}"

LOG_DIR="${LOG_DIR:-$ALIGNMENT_DIR/logs}"
HOST_LOG_DIR="${HOST_LOG_DIR:-$LOG_DIR/host}"
BACTERIA_LOG_DIR="${BACTERIA_LOG_DIR:-$LOG_DIR/bacteria}"

QC_DIR="${QC_DIR:-$ALIGNMENT_DIR/qc}"
HOST_QC_DIR="${HOST_QC_DIR:-$QC_DIR/host}"
BACTERIA_QC_DIR="${BACTERIA_QC_DIR:-$QC_DIR/bacteria}"

COUNT_DIR="${COUNT_DIR:-$ALIGNMENT_DIR/counts}"
HOST_COUNT_DIR="${HOST_COUNT_DIR:-$COUNT_DIR/host}"
BACTERIA_COUNT_DIR="${BACTERIA_COUNT_DIR:-$COUNT_DIR/bacteria}"

REPORT_DIR="${REPORT_DIR:-$ALIGNMENT_DIR/reports}"
MANIFEST_DIR="${MANIFEST_DIR:-$ALIGNMENT_DIR/manifests}"
TMP_DIR="${TMP_DIR:-$ALIGNMENT_DIR/tmp}"
ARCHIVE_DIR="${ARCHIVE_DIR:-$ALIGNMENT_DIR/archive}"

SAMPLE_LIST="${SAMPLE_LIST:-$ALIGNMENT_DIR/sample_names.txt}"
SAMPLE_SHEET="${SAMPLE_SHEET:-}"
SAMPLE_MANIFEST="${SAMPLE_MANIFEST:-$MANIFEST_DIR/sample_manifest.tsv}"
FILE_INVENTORY="${FILE_INVENTORY:-$MANIFEST_DIR/file_inventory.tsv}"
REFERENCE_CHECKSUMS="${REFERENCE_CHECKSUMS:-$MANIFEST_DIR/reference_checksums.sha256}"
REFERENCE_VERSIONS="${REFERENCE_VERSIONS:-$MANIFEST_DIR/reference_versions.tsv}"
TOOL_VERSIONS="${TOOL_VERSIONS:-$MANIFEST_DIR/tool_versions.tsv}"

THREADS="${THREADS:-16}"
READ_OVERHANG="${READ_OVERHANG:-149}"

HOST_FASTA_SOURCE="${HOST_FASTA_SOURCE:-$REF_DIR/GCF_000001405.40_GRCh38.p14_genomic.fna}"
BACTERIA_FASTA_SOURCE="${BACTERIA_FASTA_SOURCE:-$REF_DIR/AL111168.1.fasta}"
HOST_ANN_SOURCE="${HOST_ANN_SOURCE:-$REF_DIR/GCF_000001405.40_GRCh38.p14_genomic.gtf}"
BACTERIA_ANN_SOURCE="${BACTERIA_ANN_SOURCE:-$REF_DIR/AL111168.1.gff3}"

PIPELINE_VERSION="${PIPELINE_VERSION:-0.1.0}"
STAR_VERSION_PIN="${STAR_VERSION_PIN:-2.7.11b}"
SAMTOOLS_VERSION_PIN="${SAMTOOLS_VERSION_PIN:-1.20}"
SUBREAD_VERSION_PIN="${SUBREAD_VERSION_PIN:-2.0.6}"
MULTIQC_VERSION_PIN="${MULTIQC_VERSION_PIN:-1.25.1}"
